### ISSUE TITLE
containerize the bot and setup github workflow

### ISSUE THREAD

**Issue by alias-rahil** [csivitu/devspace-bot#2]
1. Make a Dockerfile
2. Setup github actions for CI/CD

**Comment by alias-rahil** [comment]
LMK if u want any resource links for this

**Comment by UnknownAbyss** [comment]
Please can I not? :(

**Comment by alias-rahil** [comment]
What about @Mannan-Goyal? Anyone else from @csivitu/csi-technical-2021-22 want to take this up?
